Shop/Entities/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Caching;
using Shop.Models;

namespace Shop.Entities
{
    public class Item
    {
        [Key]
        public long Id { get; set; }

        [MaxLength(100)]
        [Required]
        public string Name { get; set; }

        [MaxLength(1000)]
        public string Description { get; set; }

        [Required]
        public decimal Price { get; set; }
 
        public Currency Currency { get; set; }
   
        public bool Negotiable { get; set; }

        public virtual List<Photo> Photos { get; set; }
        public Category Category { get; set; }

        [Required]
        public byte CategoryId { get; set; }

        [Required]
        public string OwnerId { get; set; }
    
        public ApplicationUser Owner { get; set; }

        public ItemStatus Status { get; set; }
    }
}

Shop/Controllers/Api/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using System.Web.Http.Results;
using Microsoft.AspNet.Identity;
using Shop.Services;

namespace Shop.Controllers.Api
{
    public class ItemController : ApiController
    {
        private readonly ITransactionService _transactionService;

        public ItemController(ITransactionService transactionService)
        {
            _transactionService = transactionService;
        }

        [Route("api/item/getAmountOfItemsInChart")]
        [HttpGet]
        public JsonResult<int> GetAmountOfItemsInChart()
        {
            var loggedIn = HttpContext.Current.User.Identity.IsAuthenticated;
            if (loggedIn == false)
                return Json(0);

            var currentUserId = HttpContext.Current.User.Identity.GetUserId();
            int amountOfItems = _transactionService.GetAmountOfItemsInChartByUserId(currentUserId);

            return Json(amountOfItems);
        } 

    }
}

Shop/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Shop.Models;
using Shop.Services;

namespace Shop.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        private readonly IChatService _chatService;
        public ChatController(IChatService chatService)
        {
            _chatService = chatService;
        }
        public ActionResult ShowChat(string partnerUserId)
        {
            string currentUserId = HttpContext.User.Identity.GetUserId();
            int connectionId = _chatService.SetConnection(currentUserId, partnerUserId);
            ChatViewModel chatViewModel = _chatService.GetChatViewModel(connectionId, partnerUserId);

            return View(chatViewModel);
        }
    }
}

Shop/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Shop.Dtos;
using Shop.Entities;
using Shop.Models;
using Shop.Services;
using X.PagedList;

namespace Shop.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        private readonly IItemService _itemService;
        private readonly IPhotoService _photoService;
        private readonly ITransactionService _transactionService;

        public ItemController(IItemService itemService, IPhotoService photoService, ITransactionService transactionService)
        {
            _itemService = itemService;
            _photoService = photoService;
            _transactionService = transactionService;
        }
       
        public ActionResult AddItem()
        {
            ItemFormViewModel viewModel = _itemService.GetItemFormViewModel();
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddItem([Bind(Prefix = "ItemFormDto")] ItemFormDto itemFormDto)
        {    
            if (!ModelState.IsValid)
            {
                ItemFormViewModel viewModel = _itemService.GetItemFormViewModel();
                viewModel.ItemFormDto = itemFormDto;
                return View(viewModel);
            }

            long itemId = _itemService.AddItemAndReturnId(itemFormDto);
            _photoService.UploadPhotos(itemId, itemFormDto.PhotosList);

            return RedirectToAction("Index", "Home");
        }


        [HttpPost]
        public JsonResult UploadPhotoToTempDirectory()
        {
            HttpPostedFileBase fileUpload = Request.Files[0];   
            if (fileUpload != null && fileUpload.ContentLength > 0)
            {
                var photoName = Guid.NewGuid() + "_" + fileUpload.FileName;
                fileUpload.SaveAs(_photoService.GetTempImagePath(photoName));
                return Json(new { success = photoName });
            }
            return Json(new { success = "" });
        }

        public ActionResult SearchItem(string query, byte categoryId = 0, int pageIndex = 1)
        {
            IPagedList<ShowItemViewModel> foundItemsViewModel = _itemService.GetItemsBySearchQueryAndCategoryId(query, categoryId, pageIndex);
            return View(foundItemsViewModel);
        }

        public ActionResult ShowItemOffer(long itemId)
        {
            ShowItemViewModel showItemViewModel = _itemService.GetShowItemViewModel(itemId);
            return View(showItemViewModel);
        }

        public ActionResult BuyItem(long itemId)
        {
            _itemService.AddItemToCart(itemId);
            return RedirectToAction("Index", "Home");
        }

        public ActionResult ShowCart()
        {
            string currentUserId = HttpContext.User.Identity.GetUserId();
            List<ShowItemViewModel> showItemsViewModel = _transactionService.GetBoughItemsByUser(currentUserId);
            return View(showItemsViewModel);
        }

        public ActionResult MyOffers()
        {
            string currentUserId = HttpContext.User.Identity.GetUserId();
            List<ShowItemViewModel> showItemsViewModel = _itemService.GetItemOffersByOwnerId(currentUserId);
            return View(showItemsViewModel);
        }

        //public ActionResult FinalizeAuction(long itemId)
        //{
        //    _itemService.ChangeItemStatusToBought(itemId);
        //    _transactionService.ChangeTransactionStatusToFinalized(itemId);

        //}




    }
}

Shop/Views/Item/AddItem.cshtml
@using Shop.Resources
@model Shop.Models.ItemFormViewModel



@using (Html.BeginForm("AddItem","Item", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new {@class = "text-danger"})


    <div class="page-register-container">
        
        <div class="row">
            <div class="col-xs-offset-11 col-xs-8 header add-item-header">
                @ResourcesPolish.AddItem_AddNewItem
            </div>
        </div>

        <div class="row">
            <div class="col-xs-offset-10 col-xs-10 add-item-section">
                <div class="section1">
                    <div class="add-item-section-header">&nbsp &nbsp @ResourcesPolish.AddItem_BasicData</div>
                    <div class="row">
                        <div class="col-xs-offset-2 col-xs-28 add-item-field-label">@ResourcesPolish.AddItem_Name</div>
                        <div class="col-xs-offset-2 col-xs-26">
                            @Html.EditorFor(model => model.ItemFormDto.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ItemFormDto.Name, "", new { @class = "validation-error-red" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-offset-2 col-xs-28 add-item-field-label">@ResourcesPolish.AddItem_Category</div>
                        <div class="col-xs-offset-2 col-xs-26">
                            @Html.DropDownListFor(model => model.ItemFormDto.CategoryId, Model.Categories, ResourcesPolish.AddItemValidation_CategoryChoice, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ItemFormDto.CategoryId, "", new { @class = "validation-error-red" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-offset-2 col-xs-28 add-item-field-label">@ResourcesPolish.AddItem_Description</div>
                        <div class="col-xs-offset-2 col-xs-26">
                            @Html.EditorFor(model => model.ItemFormDto.Description, new { htmlAttributes = new { @class = "form-control add-item-description-textarea" } })
                            @Html.ValidationMessageFor(model => model.ItemFormDto.Description, "", new { @class = "validation-error-red" })
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-xs-offset-10 col-xs-10 add-item-section">
               <div clas="section2">
                <div class="add-item-section-header">&nbsp &nbsp @ResourcesPolish.AddItem_Price</div>
                <div class="row">
                    <div class="col-xs-30 add-item-field-label">
                        <div class="col-xs-offset-2 col-xs-12 add-item-price">
                            @Html.EditorFor(model => model.ItemFormDto.Price, new {htmlAttributes = new {@class = "form-control"}})
                            @Html.ValidationMessageFor(model => model.ItemFormDto.Price, "", new {@class = "validation-error-red"})
                        </div>
                        <div class="col-xs-6 add-item-price">
                            @Html.DropDownListFor(model => model.ItemFormDto.Currency, Model.Currencies, new {@class = "form-control"})
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-30 add-item-field-price">
                        <div class="col-xs-offset-1 col-xs-1">
                            @Html.CheckBoxFor(model => model.ItemFormDto.Negotiable)
                        </div>
                        <div class="col-xs-20 add-item-negotiable">
                            @ResourcesPolish.AddItem_Negotiable
                        </div>
                    </div>
                </div>
            </div>
          </div>
        </div>


        <div class="row">
            <div class="col-xs-offset-10 col-xs-10 add-item-section">
                <div clas="section3">
                    <div class="add-item-section-header">&nbsp &nbsp @ResourcesPolish.AddItem_Photos</div>
                    <div class="row">
                        <div class="add-item-margin-photos">
                            <div id="imageContainer" class="clearfix">
                                <div class="col-xs-offset-2 col-xs-8 add-item-photo-holder dropzone" id="photo0"></div>
                                <div class="col-xs-offset-1 col-xs-8 add-item-photo-holder dropzone" id="photo1"></div>
                                <div class="col-xs-offset-1 col-xs-8 add-item-photo-holder dropzone" id="photo2"></div>
                            </div>
                            @Html.ValidationMessageFor(model => model.ItemFormDto.PhotosList, "", new { @class = "photo-validation validation-error-red", @id = "photoListVal" })
                            <div>
                                @for (int i = 0; i < 3; i++)
                                {
                                    @Html.Hidden("ItemFormDto.PhotosList[" + @i + "]")
                                }
                            </div>
                        </div>
                    </div>
                </div>
             </div>
        </div>

        <div class="row">
            <div class="col-xs-offset-10 col-xs-15 add-item-button-position">
                <div class="col-xs-offset-11 col-xs-10">
                    <input type="submit" class="btn btn-block add-item-button-text" value="Wystaw"/>
                </div>
            </div>
        </div>
    </div>
}


@section Scripts{

@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/dropzone")

    <script type="text/javascript">

        $.validator.methods.range = function (value, element, param) {
            var globalizedValue = value.replace(",", ".");
            return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
        }

        $.validator.methods.number = function (value, element) {
            return this.optional(element) || /-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
        }
    </script>



    <script type="text/javascript">

        var photoId;
        $('.add-item-photo-holder').click(function() {
            var photoContainerId = this.id;
            photoId = photoContainerId.slice(-1);
        });

        Dropzone.autoDiscover = false;
        var options = {
            url: "/Item/UploadPhotoToTempDirectory",
            dictDefaultMessage: "",
            maxFiles: 1,
            thumbnailWidth: "112",
            thumbnailHeight: "90",
            acceptedFiles: ".jpg, .png, .jpeg",
            init: function() {
                myDropzone = this;
                this.on("success",
                    function(data) {
                        var result = eval('(' + data.xhr.responseText + ')');
                        $("#ItemFormDto_PhotosList_" + photoId + "_").attr('value', result.success);
                        $("#photoValidation").text('');
                        $("#photoListVal").text('');
                    });
                this.on("error",
                    function() {
                        alert("Photo uploading error!");
                    });
            }
        }


        $("div#photo0").dropzone(options);
        $("div#photo1").dropzone(options);
        $("div#photo2").dropzone(options);
      
    </script>

}

Shop/Views/Item/MyOffers.cshtml
@using Shop.Resources
@using Shop.Entities
@model List<Shop.Models.ShowItemViewModel>


<div class="cart-container">
    <div class="row">
        <div class="col-xs-offset-11 col-xs-8 header add-item-header">
            @ResourcesPolish.MyOffers
        </div>
    </div>

    <div class="row">
        <div class="col-xs-offset-2 col-xs-26">
            <div class="col-xs-30">
                <div class="table-style">
                    <div class="col-xs-6 bor">
                        @ResourcesPolish.AddItem_Name
                    </div>
                    <div class="col-xs-6 bor">
                        @ResourcesPolish.Price
                    </div>
                    <div class="col-xs-6 bor">
                        @ResourcesPolish.Status
                    </div>
                    <div class="col-xs-6 bor">
                        @ResourcesPolish.End
                    </div>
                    <div class="col-xs-6 bor">
                        @ResourcesPolish.Action
                    </div>
                </div>
            </div>
        </div>
    </div>

    @foreach (var item in Model)
    {
        <div class="row">
            <div class="col-xs-offset-2 col-xs-26">
                <div class="col-xs-30">
                    <div class="info-style">
                        <div class="col-xs-6 bor cursor" onclick="location.href = '@Url.Action("ShowItemOffer", new {@itemId = item.Id})'">
                            <span data-toggle="tooltip" data-container="body" data-placement="bottom" title="@item.Name">@(item.Name.Length > 20 ? item.Name.Substring(0, 19) : item.Name)</span>
                        </div>
                        <div class="col-xs-6 bor">
                            @item.Price @item.Currency
                        </div>
                        <div class="col-xs-6 bor cursor">
                            @item.Status.ToDescription()
                        </div>
                        <div class="col-xs-6 bor cursor">
                            <span data-toggle="tooltip" data-container="body" data-placement="bottom" title="Zakończ aukcję">
                              <span class="warn" data-toggle="modal" data-target="#myModal">@ResourcesPolish.EndOffer</span>
                            </span>
                        </div>
                        <div class="col-xs-6 bor warn">
                            <span class="warn">@ResourcesPolish.ReportProblem</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog modal-sm">
                <div class="modal-content modal-font">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Czy na pewno chcesz zakończyć aukcję przedmiotu: @item.Name ?</h4>
                    </div>
                    <div class="modal-body">
                        <p>Operacja jest nieodwracalna. Akceptacja zgodnie z regulaminem oznacza, że transakcja z kupującym dobiegła pomyślnego zakończenia.</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal" onclick="location.href='@Url.Action("FinalizeAuction", new {@itemId = item.Id})'">@ResourcesPolish.Finalize</button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">@ResourcesPolish.Back</button>
                    </div>
                </div>
            </div>
        </div>




    }
</div>




@section Scripts{

    <script>
    $(document).ready(function () {
        $("body").tooltip({ selector: '[data-toggle=tooltip]' });
    });
    </script>


}

Shop/Views/Item/SearchItem.cshtml
@model IEnumerable<Shop.Models.ShowItemViewModel>
@using System.Configuration
@using X.PagedList
@using X.PagedList.Mvc
@using Shop.Entities
@using Shop.Resources


<div class="row">
    <div class="col-xs-offset-11 col-xs-8 header search-result-header">
        Znalezione oferty
    </div>
</div>



@foreach (var item in Model)
{
        <div class="col-xs-offset-5 col-xs-20 item-offer-section" onclick="location.href='@Url.Action("ShowItemOffer", new {@itemId = item.Id})'">
            <div class="col-xs-4 main-photo-section">
                <img src="@item.MainPhotoPath" class="search-item-photo"/>
            </div>
            <div class="col-xs-25">
                <div class="col-xs-30 search-item-name">@item.Name</div>
                <div class="col-xs-30 search-item-description">
                    @if (item.Description?.Length > 150)
                    {
                        @item.Description.Substring(0, 150)
                    }
                    else
                    {
                        @item.Description
                    }
                </div>                            
              <div class="col-xs-10 search-item-price">@item.Price @item.Currency</div>                           
           </div>        
       </div>
}


<div class="row">
    <div class="col-xs-offset-5 col-xs-25 paging-style">
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("SearchItem", new { query = Request.Params["query"], pageIndex = page }),
                new PagedListRenderOptions
                {
                    MaximumPageNumbersToDisplay = Convert.ToInt32(ConfigurationManager.AppSettings["maximumPageNumbersToDisplayOnPager"]),
                    LinkToPreviousPageFormat = ResourcesPolish.PreviousPage,
                    LinkToNextPageFormat = ResourcesPolish.NextPage,
                    DisplayLinkToFirstPage = PagedListDisplayMode.Never,
                    DisplayLinkToLastPage = PagedListDisplayMode.Never,
                    DisplayEllipsesWhenNotShowingAllPageNumbers = false,
                    Display = PagedListDisplayMode.IfNeeded
                })
    </div>
</div>

Shop/Views/Item/ShowCart.cshtml
@using Shop.Resources
@model List<Shop.Models.ShowItemViewModel>


<div class="cart-container">
    <div class="row">
        <div class="col-xs-offset-11 col-xs-8 header add-item-header">
            @ResourcesPolish.My_Bin
        </div>
    </div>

    <div class="row">
        <div class="col-xs-offset-2 col-xs-26">
            <div class="col-xs-30">
                <div class="table-style">
                    <div class="col-xs-6 bor">
                        @ResourcesPolish.AddItem_Name
                    </div>
                    <div class="col-xs-6 bor">
                        @ResourcesPolish.Price
                    </div>
                    <div class="col-xs-6 bor">
                        @ResourcesPolish.Seller
                    </div>
                    <div class="col-xs-6 bor">
                        @ResourcesPolish.Contact
                    </div>
                    <div class="col-xs-6 bor">
                        @ResourcesPolish.Action
                    </div>
                </div>
            </div>
        </div>
    </div>

            @foreach (var item in Model)
            {
                <div class="row">
                    <div class="col-xs-offset-2 col-xs-26">
                        <div class="col-xs-30">
                          <div class="info-style">
                              <div class="col-xs-6 bor cursor" onclick="location.href = '@Url.Action("ShowItemOffer", new { @itemId = item.Id})'">                              
                                  <span data-toggle="tooltip" data-container="body" data-placement="bottom" title="@item.Name">@(item.Name.Length > 20 ? item.Name.Substring(0, 19) : item.Name)</span>
                              </div>
                            <div class="col-xs-6 bor">
                                @item.Price @item.Currency
                            </div>
                            <div class="col-xs-6 bor cursor">
                                <span data-toggle="tooltip" data-container="body" data-placement="bottom" title="@item.Login">@(item.Login.Length > 20 ? item.Login.Substring(0, 19) : item.Login)</span>
                            </div>
                            <div class="col-xs-6 bor cursor">
                                  <span data-toggle="tooltip" data-container="body" data-placement="bottom" title="@item.Email">@(item.Email.Length > 20 ? item.Email.Substring(0, 19) : item.Email)</span>
                            </div>
                              <div class="col-xs-6 bor warn">
                                 <span class="warn">@ResourcesPolish.ReportProblem</span>                       
                              </div>
                        </div>
                      </div>
                   </div>
                </div>
            }


    </div>


@section Scripts{

<script>
    $(document).ready(function () {
        $("body").tooltip({ selector: '[data-toggle=tooltip]' });
    });
</script>


}

Shop/Views/Item/ShowItemOffer.cshtml
@model Shop.Models.ShowItemViewModel
@using Microsoft.AspNet.Identity
@using Shop.Entities
@using Shop.Resources


<div class="col-xs-30 offer-container">
    <div class="col-xs-offset-1 item-name-section">@Model.Name</div>

    <div class="row upper-panel">
        <div class="col-xs-offset-1 col-xs-10 photos-container">      
            <div class="demo">
                <ul id="lightSlider">
                    @for(int i = 0; i < Model.Photos.Count ; i++)
                    {
                        <li data-thumb="@Model.PhotoPath(@Model.Photos[i].Id)" class="li-lightslider">
                            <img src="@Model.PhotoPath(@Model.Photos[i].Id)" class="lightslider-photo" />
                        </li>
                    }
                </ul>
            </div>           
        </div>

        <div class="col-xs-offset-1 col-xs-18 info-container">
            <div class="row">
                <div class="col-xs-15">
                    <div class="row">
                        <div class="col-xs-6 price-text">@ResourcesPolish.Price</div>
                    </div>
                    <div class="row">
                        <div class="col-xs-20 price">@Model.Price @Model.Currency</div>
                    </div>
                    <div class="row">
                        <div class="col-xs-14 button-pos">
                            @if (Model.Negotiable)
                            {
                                <input type="button" class="btn btn-warning btn-block negotiable-button" value="Negocjuj">
                            }
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-14 button-buy-pos">
                            @if (Model.Status == ItemStatus.Active)
                            {
                                <input type="button" class="btn btn-warning btn-block negotiable-button" data-toggle="modal" data-target="#myModal" value="Kupuję">
                            }
                        </div>
                    </div>
                </div>
                <div class="col-xs-15">
                    <div class="seller-info">
                        <div class="row">
                            <div class="col-xs-6 seller-text">@ResourcesPolish.Seller</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-30 seller-login">@Model.Login</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-17 button-pos">
                                <input type="button" class="btn btn-warning btn-block negotiable-button" value="Zadaj pytanie" onclick="location.href='@Url.Action("ShowChat","Chat", new { @partnerUserId = @Model.OwnerId})'">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row down-panel">
        <div class="col-xs-offset-1 col-xs-10">
            <ul class="w3-navbar w3-colors">
                <li><a href="javascript:void(0)" onclick="showTab('description')">Opis</a></li>
                <li><a href="javascript:void(0)" onclick="showTab('sellerInfo')" style="padding-right: 22px">Informacje o sprzedającym</a></li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-offset-1 col-xs-20 tab description" id="description">
            @Model.Description
        </div>

        <div class="col-xs-offset-1 col-xs-20 tab owner-info" id="sellerInfo" style="display: none">
            <div class="row">
                <div class="col-xs-7 seller-info-label">@ResourcesPolish.Seller:</div>
                <span class="seller-info-text">@Model.Login</span>                 
            </div>
            <div class="row">
                <div class="col-xs-7 seller-info-label">Kontakt:</div>
                <span class="seller-info-text">@Model.Email</span>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content modal-font">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Czy na pewno chcesz kupić przedmiot: @Model.Name ?</h4>
            </div>
            <div class="modal-body">
                <p>Operacja jest nieodwracalna</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal" onclick="location.href='@Url.Action("BuyItem", new {@itemId = Model.Id})'">@ResourcesPolish.I_Buy</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">@ResourcesPolish.Back</button>
            </div>
        </div>
    </div>
</div>


@section Scripts{ 
    <script src="~/Scripts/lightslider.js"></script>
  
    <script>     
        $('#lightSlider').lightSlider({
            gallery: true,
            item: 1,
            loop: true,
            slideMargin: 0,
            thumbItem: 9
        });

        function showTab(tabName) {
            var i;
            var x = document.getElementsByClassName("tab");
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            document.getElementById(tabName).style.display = "block";
        }

    </script>
}